name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSHPass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to EC2
        run: |
          sshpass -p "${{ secrets.EC2_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} <<EOF
            cd /home/${{ secrets.EC2_USERNAME }}/fastapi-book-project
            git pull origin main
            /home/${{ secrets.EC2_USERNAME }}/fastapi-book-project/venv/bin/pip install -r requirements.txt
            sudo systemctl restart fastapi
          EOF
