name: Deploy API
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Install Expect
        run: sudo apt-get update && sudo apt-get install -y expect
        
      - name: Deploy to EC2 with Expect
        env:
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_PASSWORD: ${{ secrets.EC2_PASSWORD }}
        run: |
          expect <<EOF
          spawn ssh -o StrictHostKeyChecking=no \$EC2_USERNAME@\$EC2_PUBLIC_IP
          expect "password:"
          send "\$EC2_PASSWORD\r"
          expect "$ "
          send "cd /home/\$EC2_USERNAME/fastapi-book-project\r"
          expect "$ "
          send "git pull origin main\r"
          expect "$ "
          send "source venv/bin/activate\r"
          expect "$ "
          send "pip install -r requirements.txt\r"
          expect "$ "
          send "sudo systemctl restart fastapi\r"
          expect "$ "
          send "exit\r"
          expect eof
          EOF